pipeline {
    agent {
        kubernetes {
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              containers:
              - name: sonar-scanner
                image: sonarsource/sonar-scanner-cli
                command:
                - cat
                tty: true
              - name: docker-build
                image: docker:latest
                command:
                - cat
                tty: true
                volumeMounts:
                - name: docker-sock
                  mountPath: /var/run/docker.sock
              - name: trivy
                image: aquasec/trivy:latest
                command:
                - cat
                tty: true
              - name: git
                image: alpine/git:latest
                command:
                - cat
                tty: true
              volumes:
              - name: docker-sock
                hostPath:
                  path: /var/run/docker.sock
            """
        }
    }
    environment {
        DOCKER_IMAGE = "caiohenrks/python-crud"
        DOCKER_TAG = "${env.BUILD_NUMBER}"
        DEPLOYMENT_FILE = "kubernetes/deployment.yaml"
        GIT_REPO = "https://github.com/Caiohenrks/pipeline-k8s-boilerplate.git"
        GIT_BRANCH = "master"
        KUBERNETES_DEPLOYMENT = "python-crud-deployment"
        KUBERNETES_NAMESPACE = "default"
    }
    stages {
        stage('Code Quality Analysis') {
            steps {
                container('sonar-scanner') {
                    script {
                        withCredentials([string(credentialsId: 'SONARQUBE', variable: 'SONARQUBE')]) {
                            sh """
                                sonar-scanner \
                                -Dsonar.projectKey=${JOB_NAME} \
                                -Dsonar.organization=caiohenrks \
                                -Dsonar.projectVersion=V${BUILD_NUMBER} \
                                -Dsonar.host.url=https://sonarcloud.io/ \
                                -Dsonar.login=${SONARQUBE}
                            """
                            sleep 15
                            def qualityGate = sh(script: "curl -k -u ${SONARQUBE}: https://sonarcloud.io/api/qualitygates/project_status?projectKey=${JOB_NAME}", returnStdout: true).trim()
                            echo "Quality Gate JSON: ${qualityGate}"
                            def status = new groovy.json.JsonSlurper().parseText(qualityGate).projectStatus.status
                            if (status != 'OK') {
                                error "Qualidade do código não atingiu o nível esperado: ${status}"
                            }
                        }
                    }
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                container('docker-build') {
                    script {
                        sh "docker build -t ${DOCKER_IMAGE}:${DOCKER_TAG} ."
                    }
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                container('docker-build') {
                    script {
                        docker.withRegistry('', 'dockerhub-credentials') {
                            sh "docker push ${DOCKER_IMAGE}:${DOCKER_TAG}"
                        }
                    }
                }
            }
        }
        stage('Security Image Scan') {
            steps {
                container('trivy') {
                    script {
                        // Realizar o scan de imagem sem template
                        sh """
                        trivy image \
                            --exit-code 0 \
                            --severity HIGH,CRITICAL \
                            ${DOCKER_IMAGE}:${DOCKER_TAG}
                        """
                    }
                }
            }
        }
        stage('Update Deployment YAML') {
            steps {
                container('docker-build') {
                    script {
                        sh "sed -i \"s|image: .*|image: ${DOCKER_IMAGE}:${DOCKER_TAG}|\" ${DEPLOYMENT_FILE}"
                    }
                }
            }
        }
        stage('Commit and Push Changes') {
            steps {
                container('git') {
                    script {
                        withCredentials([string(credentialsId: 'github-token', variable: 'GITHUB_TOKEN')]) {
                            sh """
                            git config --global --add safe.directory /home/jenkins/agent/workspace/${JOB_NAME}
                            git config --global user.email \"jenkins@example.com\"
                            git config --global user.name \"Jenkins\"
                            git checkout ${GIT_BRANCH}
                            git add ${DEPLOYMENT_FILE}
                            git commit -m \"Update deployment image to ${DOCKER_IMAGE}:${DOCKER_TAG}\"
                            git push https://${GITHUB_TOKEN}@github.com/Caiohenrks/pipeline-k8s-boilerplate.git ${GIT_BRANCH}
                            """
                        }
                    }
                }
            }
        }
    }
}
